Auto-reconnect to last connected Bluetooth device
tierneytim/btAudio pull request #23
Opened 2022-06-28 01:51 UTC by qwertychouskie

Stores the BT address in flash memory, so auto-connection can work across power cycles.  Only writes address to flash if it differs from the previously stored address, to avoid unnecessary flash wear.

2022-06-29 21:11 UTC, tierneytim commented
This seems like a cool feature. Will test and integrate over the weekend

2022-07-14 01:07 UTC, qwertychouskie commented
@tierneytim Just wanted to check if you've had a chance to look at the code.  I have some local commits to my project (https://github.com/qwertychouskie/GM-EandC-Cemu-v2) that I want to push, but was going to wait until the library changes were merged first.
Thanks for your work on this project!

2022-07-14 10:04 UTC, tierneytim commented
Unfortunately I have not been well recently so I haven't had a chance to review but will get to it before Friday

2022-07-14 15:30 UTC, tierneytim requested changes
Ok so I have had a look and think it's a great feature but I'm not sure embedding it in the begin method is the right way forward (as that makes it the default behavior beyond user control). 

Could you write two separate methods? One would check for an address in the object and save it if it was there. The other method would attempt a connection to whatever is currently saved(maybe in the reconnect method). Then users can choose whether to have this functionality or not?

Does that make sense?

2022-07-19 20:45 UTC, qwertychouskie commented
I made some changes and tested, everything still works in my project.  Should be ready for review again.

2022-07-26 18:09 UTC, tierneytim approved these changes
great work

2022-07-26 18:09 UTC, merged

2022-07-26 18:42 UTC, qwertychouskie commented
Thanks for the merge!